### ISSUE TITLE
Error: Too many values to unpack

### ISSUE THREAD

**Issue by Snigdha-Agarwal** [nyu-dl/dl4chem-geometry#1]
When running PredX_train.py with all default values and using given [QM9](https://drive.google.com/open?id=1binBToSjICL070l4sQ84kiVQHh5wFkMx) data, error faced at Line: `[D1, D2, D3, D4, D5] = pkl.load(open(molvec_fname,'rb')). `
Specifically at the following code segment in sparse/coo/core.py:
```python    
def __setstate__(self, state): 
        self.coords, self.data, self.shape, self.fill_value = state
        self._cache = None
```
What could be the reason for this issue?

**Comment by mansimov** [comment]
It looks like you are not unpacking the right number of variables when loading the QM9 data.
try running `x = pkl.load(open(molvec_fname,'rb')); print (len(x))` so see how many variables are there and let me know.

also do you see this issue with COD data ?

**Comment by Snigdha-Agarwal** [comment]
I tried doing that. The error persisted. I then modified `sparse/coo/core.py` to:

```python
    def __setstate__(self, state):
        self.coords = state['coords']
        self.data = state['data']
        self.shape = state['shape']
        self.fill_value = 0
        self._cache = None
```
Now it works fine. 
I did not try with COD data yet.

**Comment by Mazzza** [comment]
I had the same issue on COD data. 
Changing `sparse/coo/core.py` as above works.

**Comment by mansimov** [comment]
Thanks @Snigdha-Agarwal for figuring it out :)
